# CDS-Vis Session 1 - Introduction to Python

In [1]:
text_snippet = "I <3 Rocket League,"

In [2]:
text_snippet.upper()

'I <3 ROCKET LEAGUE,'

In [3]:
text_snippet.lower()

'i <3 rocket league,'

In [4]:
text_snippet.split()

['I', '<3', 'Rocket', 'League,']

In [5]:
text_snippet.split(",")

['I <3 Rocket League', '']

In [6]:
type(text_snippet.split(","))

list

# Sequence types - list

In [7]:
colours = ["blue", "green", "red"]

In [8]:
print(colours[2], colours[1], colours[0])

red green blue


In [9]:
type(colours[1])

str

In [10]:
colours[-1]

'red'

In [11]:
print(colours[-1], colours[-2],colours[-3])

red green blue


In [12]:
colours.append("yellow")

In [13]:
colours

['blue', 'green', 'red', 'yellow']

In [14]:
colours.remove("yellow")

In [15]:
colours

['blue', 'green', 'red']

### Tuples

In [16]:
colours_tup = ("blue", "green", "red")
colours_tup

('blue', 'green', 'red')

Tuples are fixed they can't change or be altered

# Dictionaries / (also called map)

In [17]:
user_ages = {
    "Albin": 23, 
    "Victor":24}

In [18]:
print(user_ages["Albin"],
user_ages["Victor"])

23 24


In [19]:
new_users = dict(
    Albin=[23,185],
    Victor=[24,196]
)

In [20]:
print(new_users["Albin"][1],"\n", new_users["Victor"][1])

185 
 196


In [21]:
new_users = dict(
    Albin={'age':23, 'height':185},
    Victor={'age':24, 'height':196}
)

In [22]:
new_users["Victor"]["age"]

24

# Number types

int = "2"
float = "2.3"

In [23]:
print(type(2))
print(type(2.1))
print("Notice this one:", type(2.0))

# Int equal to float?..    Yes it is
2 == 2.0

<class 'int'>
<class 'float'>
Notice this one: <class 'float'>


True

In [24]:
float(2)

2.0

In [25]:
int(2.9999999999)

2

In [32]:
print(
    round(2.99)
)

3


In [30]:
print(10//2) #Floor division
print(10/2)

5
5.0


# Boolean (BOOL) types
#### 0 or 1 
#### True or False

In [40]:
print("\n", True == 1,"\n", False == 0)


 True 
 True


In [41]:
print("Hej" == 0)

False


# Introducing ```numpy``` arrays

In [43]:
import numpy as np
import os 

In [50]:
#create file path

filepath = os.path.join("..",
                        "..",
                        "cds-vis-data",
                        "data","sample-data",
                        "sample-data-01.csv")

In [51]:
data = np.loadtxt(fname=filepath, delimiter=",")

In [52]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [53]:
type(data)

numpy.ndarray

In [55]:
#d-type = data type
data.dtype

dtype('float64')

In [58]:
data.shape

# 60 Rows (Going down)
# 40 Columns (Going Right)

(60, 40)

In [59]:
data[0,0]

0.0

In [65]:
data[0:4,0:10]

array([[0., 0., 1., 3., 1., 2., 4., 7., 8., 3.],
       [0., 1., 2., 1., 2., 1., 3., 2., 2., 6.],
       [0., 1., 1., 3., 3., 2., 6., 2., 5., 9.],
       [0., 0., 2., 0., 4., 2., 2., 1., 6., 7.]])

In [66]:
#select whole row options :))

data[0,:]


array([ 0.,  0.,  1.,  3.,  1.,  2.,  4.,  7.,  8.,  3.,  3.,  3., 10.,
        5.,  7.,  4.,  7.,  7., 12., 18.,  6., 13., 11., 11.,  7.,  7.,
        4.,  6.,  8.,  8.,  4.,  4.,  5.,  7.,  3.,  4.,  2.,  3.,  0.,
        0.])

In [67]:
#select whole columns options :))

data[:,0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [69]:
# average, max score

print(np.mean(data), np.max(data))



6.14875 20.0


In [71]:
#max for every patiens

np.max(data, axis=1)



# other axis (for every column) has axis-number 0

array([18., 18., 19., 17., 17., 18., 17., 20., 17., 18., 18., 18., 17.,
       16., 17., 18., 19., 19., 17., 19., 19., 16., 17., 15., 17., 17.,
       18., 17., 20., 17., 16., 19., 15., 15., 19., 17., 16., 17., 19.,
       16., 18., 19., 16., 19., 18., 16., 19., 15., 16., 18., 14., 20.,
       17., 15., 17., 16., 17., 19., 18., 18.])